name: Update Cruft Project

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours
  repository_dispatch:
    types:
      - cruft-update

jobs:
  update:
    runs-on: [ "ubuntu-latest" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Cruft
        run: pip3 install cruft

      - name: Check and Update Cruft projects in subdirectories
        run: |
          git config --global user.name "cruft[bot]"
          git config --global user.email "cruft[bot]@users.noreply.github.com"
          git config --global url."https://${{ secrets.CRUFT_GITHUB_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

          UPDATED=false

          # Find directories with .cruft.json and loop over them
          while IFS= read -r dir; do
            # Extract just the directory path
            dir=$(dirname "$dir")

            # Navigate into the directory
            cd "$dir"

            # Check if cruft update is available
            if ! cruft check; then
              # If available, apply the update
              cruft update --skip-apply-ask --refresh-private-variables
              git restore --staged .
              git add .
              git commit -m "chore($dir): accept new Cruft update"
              UPDATED=true
            fi

            # Navigate back to the root directory
            cd $GITHUB_WORKSPACE

          done < <(find . -name ".cruft.json" -type f)

          echo "UPDATED=$UPDATED" >> $GITHUB_ENV

      - name: Check for existing PR
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base "cruft/update-*" | wc -l)
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV

      - name: Create pull request
        if: env.UPDATED == 'true' && env.PR_EXISTS == '0'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CRUFT_GITHUB_ACCESS_TOKEN }}
          commit-message: "Update Cruft templates in subdirectories"
          branch: cruft/update
          delete-branch: true
          branch-suffix: timestamp
          title: New updates detected with Cruft
          labels: "auto-merge"
          body: |
            This is an autogenerated PR.

            [Cruft](https://cruft.github.io/cruft/) has detected updates from the Cookiecutter repository in multiple subdirectories.
